# Generated by Django 5.0.7 on 2024-08-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maths', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=100)),
                ('malayalam', models.CharField(max_length=100)),
                ('hindi', models.CharField(max_length=100)),
            ],
        ),
    ]
